AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.9
    Environment:
      Variables:
        TELEGRAM_TOKEN: !Sub "${botToken}"
        TABLE_NAME:
          Ref: MainTable

Parameters:
  botToken:
    Type: String

Resources:
  # Lambda Layers
  MainLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: main_layer
      ContentUri: src/layers/main_layer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  # Lambda functions
  SendPoll:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/polling
      Handler: main.handler
      Layers:
        - !Ref MainLayer
      Policies:
        - Statement:
            - Sid: DynamodbPolicy
              Effect: Allow
              Action:
                - "dynamodb:Query"
                - "dynamodb:DescribeTable"
                - "dynamodb:PutItem"
                - "dynamodb:UpdateItem"
              Resource: !GetAtt MainTable.Arn
  UpdatesHandler:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/handlers/messages
      Handler: main.handler
      Layers:
        - !Ref MainLayer
      Events:
        ProcessMessage:
          Type: Api
          Properties:
            Path: /messages
            Method: post
      Environment:
        Variables:
          POLLING_LAMBDA_ARN: !GetAtt SendPoll.Arn
      Policies:
        - Statement:
            - Sid: DynamodbPolicy
              Effect: Allow
              Action:
                - "dynamodb:GetItem"
                - "dynamodb:PutItem"
                - "dynamodb:Query"
                - "dynamodb:UpdateItem"
                - "dynamodb:DescribeTable"
                - "dynamodb:DeleteItem"
              Resource: !GetAtt MainTable.Arn
        - Statement:
            - Sid: EventBridgePolicy
              Effect: Allow
              Action:
                - "events:PutRule"
                - "events:PutTargets"
                - "events:DescribeRule"
              Resource: "*"
        - Statement:
            - Sid: LambdaPermissionsPolicy
              Effect: Allow
              Action:
                - "lambda:AddPermission"
              Resource: !GetAtt SendPoll.Arn
        - Statement:
            - Sid: TranslatePermissionsPolicy
              Effect: Allow
              Action:
                - "translate:TranslateText"
              Resource: "*"

  # DynamoDB
  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
