AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 60
    Runtime: python3.9
    Environment:
      Variables:
        TELEGRAM_TOKEN: !Sub "${botToken}"
        TABLE_NAME:
          Ref: MainTable
        ADMIN_IDS: !Sub "${AdminIds}" # Comma separated list
        API_NINJAS_API_KEY: !Sub "${ApiNinjasApiKey}"


Parameters:
  botToken:
    Type: String
  AdminIds:
    Type: String
  ApiNinjasApiKey:
    Default: ""
    Type: String


Resources:
  # Lambda Layers
  MainLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: main_layer
      ContentUri: src/layers/main_layer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  # Lambda functions
  SendPoll:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/polling
      Handler: main.handler
      Layers:
        - !Ref MainLayer
      Policies:
        - Statement:
            - Sid: DynamodbPolicy
              Effect: Allow
              Action:
                - "dynamodb:Query"
                - "dynamodb:DescribeTable"
                - "dynamodb:PutItem"
                - "dynamodb:UpdateItem"
                - "dynamodb:BatchWriteItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:GetItem"
#              Resource: !GetAtt MainTable.Arn
              Resource: "*"
        - Statement:
            - Sid: EventBridgePolicy
              Effect: Allow
              Action:
                - "events:DeleteRule"
                - "events:RemoveTargets"
                - "events:ListTargetsByRule"
              Resource: "*"
        - Statement:
            - Sid: LambdaPermissionsPolicy
              Effect: Allow
              Action:
                - "lambda:RemovePermission"
              Resource: "*"
  UpdatesHandler:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/handlers/messages
      Handler: main.handler
      Layers:
        - !Ref MainLayer
      Events:
        ProcessMessage:
          Type: Api
          Properties:
            Path: /messages
            Method: post
      Environment:
        Variables:
          POLLING_LAMBDA_ARN: !GetAtt SendPoll.Arn
      Policies:
        - Statement:
            - Sid: DynamodbPolicy
              Effect: Allow
              Action:
                - "dynamodb:GetItem"
                - "dynamodb:PutItem"
                - "dynamodb:Query"
                - "dynamodb:UpdateItem"
                - "dynamodb:DescribeTable"
                - "dynamodb:DeleteItem"
                - "dynamodb:BatchWriteItem"
#              Resource: !GetAtt MainTable.Arn
              Resource: "*"
        - Statement:
            - Sid: EventBridgePolicy
              Effect: Allow
              Action:
                - "events:PutRule"
                - "events:PutTargets"
                - "events:DescribeRule"
                - "events:DeleteRule"
                - "events:RemoveTargets"
                - "events:ListTargetsByRule"
              Resource: "*"
        - Statement:
            - Sid: LambdaPermissionsPolicy
              Effect: Allow
              Action:
                - "lambda:AddPermission"
                - "lambda:RemovePermission"
              Resource: !GetAtt SendPoll.Arn
        - Statement:
            - Sid: TranslatePermissionsPolicy
              Effect: Allow
              Action:
                - "translate:TranslateText"
              Resource: "*"
  SuggestionsHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/suggestions
      Handler: main.handler
      Layers:
        - !Ref MainLayer
      Events:
        SendSuggestion:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
#            Schedule: rate(3 minutes)
            Enabled: true
      Policies:
        - Statement:
            - Sid: DynamodbPolicy
              Effect: Allow
              Action:
                - "dynamodb:GetItem"
                - "dynamodb:PutItem"
                - "dynamodb:Query"
                - "dynamodb:UpdateItem"
                - "dynamodb:DescribeTable"
                - "dynamodb:DeleteItem"
                - "dynamodb:BatchWriteItem"
              Resource: "*"
        - Statement:
            - Sid: TranslatePermissionsPolicy
              Effect: Allow
              Action:
                - "translate:TranslateText"
              Resource: "*"

  # DynamoDB
  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
